import { chromium } from 'playwright';
const b = await chromium.launch({ channel: 'chrome', headless: true });
const ctx = await b.newContext({ locale: 'en-US', timezoneId: 'America/Los_Angeles' });
const p = await ctx.newPage();
await p.goto('https://www.amazon.com/dp/B0DSLWLDK5', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(2500);
console.log('GLOW (no ZIP set):', await p.$eval('#glow-ingress-line2', e=>e.textContent.trim()).catch(()=>'(none)'));
const st = await ctx.storageState();
const c = st.cookies.filter(k=>/amazon\.com$/.test(k.domain.replace(/^\./,''))).map(k=>k.name+'='+k.value).join('; ');
require('fs');
(await import('fs')).writeFileSync('/tmp/claude-501/amz_cookie_noZIP.txt', c);
console.log('NOZIP cookie bytes:', c.length);
await b.close();
